name: omnispace
description: A Flutter project for OmniSpace – the ultimate journaling hub.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.0.3

  # Hive for local data storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.0

  # Permissions
  permission_handler: ^11.3.1

  # Media capture & playback
  image_picker: ^0.8.5+3

  # Masonry / staggered grid layout for journal tiles
  flutter_staggered_grid_view: ^0.6.2

  # Calendar/date formatting
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  # Hive code generation
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
