name: omnispace
description: A spirit-driven, ecosystemic journaling & life-management app.
version: 0.1.0+1
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.0.5

  # Local persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11

  # Networking & Auth
  http: ^1.4.0

  # Permissions & media
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.2
  record: ^6.0.0
  audioplayers: ^6.4.0
  audio_waveforms: ^1.3.0
  video_player: ^2.7.2

  # Notifications & timezones
  flutter_local_notifications: ^12.0.4
  timezone: ^0.9.0
  intl: ^0.20.2

  # UI & utilities
  flutter_staggered_grid_view: ^0.7.0
  flutter_colorpicker: ^1.0.3
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code generation for Hive adapters
  build_runner: ^2.4.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
