name: omnispace
description: A unified note, tracker, and project management app with rich features.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2

  # Persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11

  # Date formatting
  intl: ^0.17.0

  # HTTP client
  http: ^0.13.6

  # Rich-text editor (downgraded to match Flutter 3.3.x)
  flutter_quill: ^5.2.0

  # State management
  provider: ^6.0.5

  # Secure storage
  flutter_secure_storage: ^8.0.0

  # Local notifications
  flutter_local_notifications: ^12.0.0

  # Timezone helper
  timezone: ^0.9.4
  flutter_native_timezone: ^2.0.0

  # Permissions
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Hive code generation
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    # - assets/images/
    # - assets/icons/
