name: omnispace
description: A unified note, tracker, and project management app with rich features.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11

  # Formatting
  intl: ^0.20.2

  # HTTP
  http: ^1.4.0

  # State
  provider: ^6.0.5

  # Secure storage & notifications
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_local_notifications: ^19.2.1

  # Timezones & permissions
  timezone: ^0.10.1
  flutter_native_timezone: ^2.0.0
  permission_handler: ^12.0.0+1

  # **New visualization libs**
  flutter_heatmap_calendar: ^1.0.5
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
