name: omnispace
description: A spirit-driven, ecosystemic journaling & life-management app.
version: 0.1.0+1
publish_to: "none" # not published

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.0.5

  # Local persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11

  # Code generation
  # (run: flutter pub run build_runner build --delete-conflicting-outputs)
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

  # Permissions & media
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.2
  record: ^6.0.0
  audioplayers: ^6.4.0
  flutter_audio_waveforms: ^1.2.1+8

  # Utilities
  flutter_colorpicker: ^1.0.3
  intl: ^0.20.2

  # UI
  flutter_staggered_grid_view: ^0.7.0
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Linting
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/journal_bg.png
    # add your other asset paths here

  # If you have font or other assets, list them here
